[package]
name = "veda-search-query"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
tokio = { version = "0.2.10", features = ["full"] }
log = "0.4"
rust-ini = "0.16"
nng = "0.5.1"
serde_json = "1.0"

v_onto = { path = "../v-onto" }
v_module = { path = "../v-module" }
v_api = { path = "../v-api" }
v_authorization = { path = "../v-authorization" }
v_az_lmdb = { path = "../v-az-lmdb" }
v_search = { path = "../v-search" }
