[package]
name = "veda-mstorage"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
rust-ini = "0.16"
nng = "0.5.1"
serde_json = "1.0"
chrono = "0.4"

v_storage = { path = "../v-storage" }
v_queue = { path = "../v-queue" }
v_onto = { path = "../v-onto" }
v_module = { path = "../v-module" }
v_api = { path = "../v-api" }
v_authorization = { path = "../v-authorization" }
v_az_lmdb = { path = "../v-az-lmdb" }
