version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run:
          name: "pre-install"
          command: | 
           sudo apt-get clean
           sudo apt-get update
           sudo apt-get install dpkg
      - run:
          name: "Install Test Env"
          command: | 
           sudo apt-get install nodejs
           sudo apt install npm
           npm install -g testcafe
           npm install grunt
           npm install grunt-contrib-qunit
           wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
           sudo dpkg -i --force-depends google-chrome-stable_current_amd64.deb
      - run:
          name: "Install"
          command: | 
           ./tools/install-tarantool.sh
           ./control-install.sh
           source $HOME/.cargo/env
           go version
           rustc -V
      - run:
          name: "Build"
          command: | 
           source $HOME/.cargo/env
           ./build.sh 
      - run:
          name: "test"
          command: | 
            ./control-start.sh
            sleep 200
            grunt test --stack --verbose
            testcafe chrome:headless qa/testcafe/testLogin.js --screenshots screens --screenshots-on-fails screens --speed 0.8
            testcafe chrome:headless qa/testcafe/testPerson.js --screenshots screens --screenshots-on-fails screens --speed 0.2
            testcafe chrome:headless qa/testcafe/testLanguage.js --screenshots screens --screenshots-on-fails screens --speed 0.8
            testcafe chrome:headless qa/testcafe/testComment.js --screenshots screens --screenshots-on-fails screens --speed 0.5
            testcafe chrome:headless qa/testcafe/testSearch.js --screenshots screens --screenshots-on-fails screens --speed 0.8
            testcafe chrome:headless qa/testcafe/testCreatingNetInterface.js --screenshots screens --screenshots-on-fails screens --speed 0.8
            testcafe chrome:headless qa/testcafe/testDeleteAndRecovery.js --screenshots screens --screenshots-on-fails screens --speed 0.7
            testcafe chrome:headless qa/testcafe/testJournal.js --screenshots screens --screenshots-on-fails screens --speed 0.8
            testcafe chrome:headless qa/testcafe/testRights.js --screenshots screens --screenshots-on-fails screens --speed 0.8
            testcafe chrome:headless qa/testcafe/testSearchRangeOfDates.js --screenshots screens --screenshots-on-fails screens --speed 0.8
            testcafe chrome:headless qa/testcafe/testSimpleNet.js --screenshots screens --screenshots-on-fails screens --speed 0.2
            testcafe chrome:headless qa/testcafe/testSimpleNet2.js --screenshots screens --screenshots-on-fails screens --speed 0.2
            testcafe chrome:headless qa/testcafe/testSimpleNet3.js --screenshots screens --screenshots-on-fails screens --speed 0.2
            testcafe chrome:headless qa/testcafe/testSimpleNetLowPriority.js --screenshots screens --screenshots-on-fails screens --speed 0.8
            testcafe chrome:headless qa/testcafe/testControls.js --screenshots screens --screenshots-on-fails screens --speed 0.8
            testcafe chrome:headless qa/testcafe/testDropDown.js --screenshots screens --screenshots-on-fails screens --speed 0.7
            testcafe chrome:headless qa/testcafe/testAttributiveSearch.js --screenshots screens --screenshots-on-fails screens --speed 0.7

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
