[package]
name = "v_api"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[lib]
path = "src/api_client.rs"

[dependencies]
serde = "1.0"
serde_json = "1.0"
nng = "0.5.1"
log = "0.4"
nanoid = "0.3.0"

v_onto = { path = "../v-onto" }
