[package]
name = "veda-input-onto"
version = "0.1.0"
authors = ["Valeriy Bushenev <ValeriyBushenev@gmail.com>"]
edition = "2018"

[[bin]]
name = "veda-input-onto"
path = "src/main.rs"

[dependencies]
log = "0.4"
ron = "0.5.1"
serde = "1.0"
rio_turtle = {git="https://github.com/semantic-machines/rio.git", rev="cab2cb9863df496478da6a247cc8403414d9e9eb"}
rio_api = "0.4"
notify = "=5.0.0-pre.1"
md-5 = "0.8.0"
hex = "0.4.0"
crossbeam-channel = "0.3.9"

v_onto = { path = "../v-onto" }
v_module = { path = "../v-module" }
v_api = { path = "../v-api" }

