[package]
name = "veda-scripts-v8"
version = "0.1.0"
authors = ["itiu <ValeriyBushenev@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4"
lazy_static = "1.4.0"
rust_decimal = "1.7.0"

# sudo apt install libglib2.0-dev
rusty_v8 = "0.13.0"

v_v8 = { path = "../v-v8" }
v_module = { path = "../v-module" }
v_storage = { path = "../v-storage" }
v_onto = { path = "../v-onto" }
v_api = { path = "../v-api" }
v_search = { path = "../v-search" }
v_ft_xapian = { path = "../v-ft-xapian" }
v_queue = { path = "../v-queue" }
